### ISSUE TITLE
please meilisearch container

### ISSUE THREAD

**Issue by vahidalvandi** [ucan-lab/docker-laravel#215]
append

```
volumes:
  meili-store:
```

```
  meilisearch:
    image: getmeili/meilisearch:v0.29
    ports:
      - target: 7700
        published: ${MEILISEARCH_PUBLISHED_PORT:-7700}
        protocol: tcp
        mode: host
    environment:
      - MEILI_MASTER_KEY=MY_API_KEY
    volumes:
      - type: volume
        source: meili-store
        target: /var/lib/meili-store
        volume:
          nocopy: true

```
