### ISSUE TITLE
Explicitly specify the context on Docker Compose

### ISSUE THREAD

**Issue by ucan-lab** [ucan-lab/docker-laravel#89]
## Before

```
services:
  app:
    build: ./infra/docker/php
```

## After

```
services:
  app:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
```

By putting the root directory in the Docker context, the Dockerfile will be able to access any file.
